name = "FFL"
uuid = "06ed1437-5cec-4b14-b88c-77563f59284f"
authors = ["Sean Kell <sean.michael.kell@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
